# Site Info
title: 'samstudy'
tagline: 'samstudy'
description: 'studying UX HCI Design'
baseurl: ""
url: https://samilulu.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: CHA MALGEUNSAM
  description: sam(CHA MALGEUNSAM)
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/samilulu
    # facebook:  https://www.facebook.com/
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:    21800714@handong.edu

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { TIL (Today I Learned): '/blog/categories/#til' }
    - { Human Factors and Ergonomics: '/blog/categories/#hfe' }
    - { Human Computer Interaction: '/blog/categories/#hci' }
    - { Smart Interface Design: '/blog/categories/#sid' }
    - { Editorial Design: '/blog/categories/#ed' }
    - { Design Tool: '/blog/categories/#dt' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
# google_analytics_token: 'UA-92094009-1' # leave blank if you don't want google analytics
disqus_short_name: 'samilulu-github-io' # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate
